# Generated by Django 6.0.4 on 2026-05-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('information', models.TextField()),
                ('status', models.CharField(choices=[('review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='review', max_length=20)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_category', models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('arts', 'Arts'), ('education', 'Education'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('food', 'Food'), ('business', 'Business'), ('charity', 'Charity'), ('social', 'Social')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
